# Generated by Django 4.1.1 on 2022-10-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComercios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com',
            name='fecha_adhesion',
            field=models.DateField(),
        ),
    ]
