# Generated by Django 4.1 on 2022-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('dni', models.IntegerField()),
                ('fecha_nac', models.DateField()),
                ('fecha_cred', models.DateField()),
                ('importe', models.FloatField()),
                ('cuotas', models.IntegerField()),
            ],
        ),
    ]
