# Generated by Django 4.1 on 2022-10-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCreditos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cre',
            name='telefono',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
