# Generated by Django 4.1.1 on 2022-10-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCreditos', '0004_res_comercio_res'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RES',
        ),
    ]
